import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/layout/layout";
import "react-toastify/dist/ReactToastify.css";
import React from "react";
import PropTypes from "prop-types";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Kitob O'qi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <Layout>{children}</Layout>
        </div>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};
